### ISSUE TITLE
Can you support adding or modifying key?

### ISSUE THREAD

**Issue by csc-EricWu** [tarappo/fastlane-plugin-ipa_info#13]

**Comment by csc-EricWu** [comment]
for Info.plist

**Comment by tarappo** [comment]
I released new feature.

example 
```
ipa_info(
  ipa_file: ${your_ipa_file_path},
  add_extract_info_plist_params: [[ "CFBundleIdentifier", "BundleIdentifier" ]]
)
```

result
```
...
+------------------+------------------------------------+
|                Info.plist Information                 |
+------------------+------------------------------------+
| Name             | Value                              |
+------------------+------------------------------------+
| BundleIdentifier | com.example.tarappo                 |
+------------------+------------------------------------+
...
```

**Comment by csc-EricWu** [comment]
I'm glad to hear that. I can't wait to test it, but I got the following error.


ipaPath = "/Users/eric/Downloads/5/youtu.ipa"

desc "功能测试"
  lane :test do
 
    ipa_info(
      ipa_file: ipaPath,
      add_extract_info_plist_params: [["ITSAppUsesNonExemptEncryption", "NO"]],
    )
  end


NFO [2021-03-12 10:42:22.93]: ------------------------------
INFO [2021-03-12 10:42:22.93]: --- Step: default_platform ---
INFO [2021-03-12 10:42:22.93]: ------------------------------
INFO [2021-03-12 10:42:22.93]: Driving the lane 'ios test' 🚀
INFO [2021-03-12 10:42:22.94]: ----------------------
INFO [2021-03-12 10:42:22.94]: --- Step: ipa_info ---
INFO [2021-03-12 10:42:22.94]: ----------------------
WARN [2021-03-12 10:42:22.94]: Lane Context:
INFO [2021-03-12 10:42:22.94]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test"}
ERROR [2021-03-12 10:42:22.94]: invalid byte sequence in UTF-8
INFO [2021-03-12 10:42:22.94]: Successfully generated documentation at path '/Users/eric/Working/testflight/fastlane/README.md'

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 💥   | ipa_info         | 0           |
+------+------------------+-------------+

DEBUG [2021-03-12 10:42:22.95]: All plugins are up to date
ERROR [2021-03-12 10:42:22.95]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

**Comment by tarappo** [comment]
@csc-EricWu 
please tell me the plugin version.

I released some versions 0.7.0、0.8.0、0.8.1.
please use 0.8.1 version.

**Comment by csc-EricWu** [comment]
[10:48:43]: $ bundle exec fastlane ipa_info
[10:48:43]: 
[10:48:43]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
+--------------------------+---------+----------+
|                 Used plugins                  |
+--------------------------+---------+----------+
| Plugin                   | Version | Action   |
+--------------------------+---------+----------+
| fastlane-plugin-ipa_info | 0.8.1   | ipa_info |
+--------------------------+---------+----------+

**Comment by tarappo** [comment]
I do not happen with my ipa files.
so please run follows action, tell me the result.

 - run without parameter
 - run with other key for add_extract_info_plist_params

**Comment by csc-EricWu** [comment]
Yes, I encountered the same error. Can you provide an email? I'll send you the IPA.

**Comment by tarappo** [comment]
okey.
my email is tarappo@gmail.com

**Comment by tarappo** [comment]
I released new version 0.8.2

**Comment by csc-EricWu** [comment]
Yes, I saw it work. But he didn't change it Info.plist Content.

for example

ipa_ info(

ipa_ file: ipaPath,

add_ extract_ info_ plist_ params: [["CFBundleIdentifier", "BundleIdentifier"]],

)

**Comment by tarappo** [comment]
If you use the param, then print the new table the follows.

```
+------------------+-----------------------+
|          Info.plist Information          |
+------------------+-----------------------+
```

what do you hope to expect?

**Comment by csc-EricWu** [comment]
Yes, I see it.

In fact, I want to change or add a key for ipa info.plist

**Comment by csc-EricWu** [comment]
Can you do it? I really need this feature.
@tarappo

**Comment by tarappo** [comment]
I understood it.

The plugin only show the information on ipa file’s some files.

If you need to exchange and add data,  I think to use the follows plugin.

https://docs.fastlane.tools/actions/update_info_plist/

**Comment by csc-EricWu** [comment]
Yes, I noticed it, but it can only change xcodeproj Info.plist . Cannot change IPA's info.plist .

I want to add the infoplist option to resgn to change it, but I can't implement it.

http://docs.fastlane.tools/actions/resign/#resign

**Comment by csc-EricWu** [comment]
update_ info_ Plist if I can change the IPA, I also need it.

**Comment by tarappo** [comment]
The plugin only show the information on ipa file’s some files.
so the plugin does not support to add or exchange Info.plist.
