### ISSUE TITLE
rubyzip version conflict in ipa_analyzer

### ISSUE THREAD

**Issue by jeremy303** [tarappo/fastlane-plugin-ipa_info#5]
I'm seeing this error, seemingly due to conflicts in the rubygem dependency of ipa_analyzer and the latest fastlane:
```
Unable to activate ipa_analyzer-0.1.0, because rubyzip-1.2.2 conflicts with rubyzip (>= 1.1.7, ~> 1.1.7) (Gem::ConflictError)
```

I understand this is really an ipa_analyzer issue, but wondered if you have any ideas on the best approach for resolution.  That project hasn't seen much activity recently.

Thanks!

**Comment by tarappo** [comment]
I think that fix ipa_analyzer or I do not use ipa_analyzer.
please wait, I may do it.

**Comment by tarappo** [comment]
I did pull request and merged.
so this gem is will release new version.
https://github.com/bitrise-io/ipa_analyzer/pull/5

**Comment by tarappo** [comment]
fix it. 
https://github.com/tarappo/fastlane-plugin-ipa_info/pull/7
https://github.com/tarappo/fastlane-plugin-ipa_info/releases/tag/v0.4.0

thanks: @HolySamosa
